### ISSUE TITLE
BindingProvider Exception for ENUMS

### ISSUE THREAD

**Issue by PinoOG** [jonahseguin/drink#19]
```
[02:05:10 ERROR]: Error occurred while enabling GrindCore v1.0 (Is it up to date?)
com.jonahseguin.drink.exception.CommandRegistrationException: Could not register command 'grind-core': No provider bound for ActionType
        at com.jonahseguin.drink.command.DrinkCommandService.register(DrinkCommandService.java:132) ~[GrindCore-1.0.jar:?]
        at net.gemoria.grindcore.GrindCore.loadCommands(GrindCore.java:162) ~[GrindCore-1.0.jar:?]
        at net.gemoria.grindcore.GrindCore.onEnable(GrindCore.java:82) ~[GrindCore-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[?:git-UniverseSpigot-"fe2588e"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[?:git-UniverseSpigot-"fe2588e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[?:git-UniverseSpigot-"fe2588e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[?:git-UniverseSpigot-"fe2588e"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:655) ~[?:git-UniverseSpigot-"fe2588e"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:566) ~[?:git-UniverseSpigot-"fe2588e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[?:git-UniverseSpigot-"fe2588e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[?:git-UniverseSpigot-"fe2588e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[?:git-UniverseSpigot-"fe2588e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[?:git-UniverseSpigot-"fe2588e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[?:git-UniverseSpigot-"fe2588e"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.jonahseguin.drink.exception.MissingProviderException: No provider bound for ActionType
        at com.jonahseguin.drink.parametric.ProviderAssigner.assignProvidersFor(ProviderAssigner.java:41) ~[GrindCore-1.0.jar:?]
        at com.jonahseguin.drink.command.DrinkCommand.<init>(DrinkCommand.java:47) ~[GrindCore-1.0.jar:?]
        at com.jonahseguin.drink.command.CommandExtractor.extractCommand(CommandExtractor.java:60) ~[GrindCore-1.0.jar:?]
        at com.jonahseguin.drink.command.CommandExtractor.extractCommands(CommandExtractor.java:29) ~[GrindCore-1.0.jar:?]
        at com.jonahseguin.drink.command.DrinkCommandService.register(DrinkCommandService.java:124) ~[GrindCore-1.0.jar:?]
```

By default Drink supports out of the box Enums for commands parameters, but when using an enum as command parameter it triggers this exception on enable

ActionType is just an enum, this is the command

    @Command(name = "data", aliases = {}, desc = "Gestione dati dei giocatori in Cache", usage = "data <ACTION> <DATA> <VALUE>")
    @Require(value = "grindcore.admin" ) //, message = "Non hai il permesso di usare il comando!")
    public void onData(@Sender CommandSender sender, ActionType actionType, DataType data, Player target, @OptArg int value){

        final OnlineUser user = OnlineUser.adapter(target);
        switch (actionType){
            case SET -> user.setData(data, value);
            case ADD -> user.addData(data, value);
            case REMOVE -> user.removeData(data, value);
        }
        sender.sendMessage("§7[§eGrindCore§7] §fValore da modificare correttamente impostato per -> "  + target.getName());
    }

**Comment by shlovto** [comment]
@NaTorOG You have to register the enum as provider, then you can use it as parameter: https://github.com/jonahseguin/drink/blob/1b60eff7e0ce03eecb9b322424779ea7e0693730/src/main/java/com/jonahseguin/drink/provider/EnumProvider.java#L15

**Comment by PinoOG** [comment]
> @NaTorOG You have to register the enum as provider, then you can use it as parameter:
> 
> https://github.com/jonahseguin/drink/blob/1b60eff7e0ce03eecb9b322424779ea7e0693730/src/main/java/com/jonahseguin/drink/provider/EnumProvider.java#L15

Thanks for replying, but I can't extend my enum to a DrinkProvider, can you explain how? Thanks for helping

**Comment by shlovto** [comment]
> > @NaTorOG You have to register the enum as provider, then you can use it as parameter:
> > https://github.com/jonahseguin/drink/blob/1b60eff7e0ce03eecb9b322424779ea7e0693730/src/main/java/com/jonahseguin/drink/provider/EnumProvider.java#L15
> 
> Thanks for replying, but I can't extend my enum to a DrinkProvider, can you explain how? Thanks for helping

Read https://github.com/jonahseguin/drink?tab=readme-ov-file#binding-providers :D

**Comment by shlovto** [comment]
I think this part should help you a little more: https://github.com/jonahseguin/drink?tab=readme-ov-file#binding-your-provider

Just use the EnumProvider as provider and bind the action enum to it

**Comment by PinoOG** [comment]
> I think this part should help you a little more: https://github.com/jonahseguin/drink?tab=readme-ov-file#binding-your-provider
> 
> Just use the EnumProvider as provider and bind the action enum to it

`drink.bind(ActionType.class).toProvider(new EnumProvider<>(ActionType.class));`

Something like this should work?

**Comment by shlovto** [comment]
> > I think this part should help you a little more: https://github.com/jonahseguin/drink?tab=readme-ov-file#binding-your-provider
> > Just use the EnumProvider as provider and bind the action enum to it
> 
> `drink.bind(ActionType.class).toProvider(new EnumProvider<>(ActionType.class));`
> 
> Something like this should work?

Yes.

**Comment by PinoOG** [comment]
It worked, thank you very much!

**Comment by shlovto** [comment]
Np, you can close the issue :D
